export type PublicPage = { eyebrow:string; title:string; description:string; sections:{title:string;body:string}[] };
export const publicPages:Record<string,PublicPage>={
  "custom-solutions":{eyebrow:"OEM / ODM",title:"Custom balloon collections, built around your market.",description:"Develop coordinated balloon products with artwork, color, language, assortment, and packaging options aligned to your sales channel.",sections:[{title:"Creative alignment",body:"Share the occasion, target market, visual direction, size, quantity, and packing requirements."},{title:"Sample confirmation",body:"Review the selected construction, printed artwork, colors, and presentation before bulk production."},{title:"Production planning",body:"Confirm the order schedule, production details, inspection arrangement, and shipping requirements."}]},
  manufacturing:{eyebrow:"Manufacturing Network",title:"Partner production depth for repeatable balloon programs.",description:"Our manufacturing partner network includes a 40,000 m² production footprint, 10 workshops, and 80 production lines supporting custom and repeat orders.",sections:[{title:"Printing",body:"Partner production resources include ten printing machines for decorative and language-specific balloon artwork."},{title:"Material processing",body:"Partner film blowing and metallizing capacity supports the preparation of balloon materials and finishes."},{title:"Finishing",body:"Partner punching and bag-making equipment supports shaping, finishing, assortments, and retail presentation."}]},
  "quality-compliance":{eyebrow:"Quality & Compliance",title:"Clear checks from material receipt to shipment.",description:"Quality requirements are confirmed per order, supported by in-process checks, final inspection, and third-party inspection coordination when requested.",sections:[{title:"Incoming materials",body:"Materials and order requirements are checked before production begins."},{title:"In-process review",body:"Printing, color, dimensions, and assembly details are reviewed during production."},{title:"Shipment inspection",body:"Final quantities, presentation, and agreed product details are checked before dispatch."}]},
  about:{eyebrow:"About PARTY HUB",title:"Celebration products backed by practical manufacturing.",description:"PARTY HUB is the export-facing balloon brand of Yiwu Xitong Trading Co., Ltd., serving international party-supply buyers from Yiwu, Zhejiang.",sections:[{title:"Our focus",body:"We develop foil balloon collections for birthdays, weddings, festivals, gifting, event decoration, and retail programs."},{title:"Our approach",body:"The team combines creative product selection with sample review, scalable production, and straightforward order communication."},{title:"Our location",body:"Yiwu connects sourcing, production, logistics, and international trade in one of China's most active commercial hubs."}]},
  faq:{eyebrow:"FAQ",title:"Useful answers for your sourcing process.",description:"Review common questions about customization, samples, quantities, lead times, inspection, and shipping preparation.",sections:[]},
  contact:{eyebrow:"Request a Quote",title:"Tell us what you are planning.",description:"Share the product, estimated quantity, target market, customization requirements, and preferred timeline.",sections:[{title:"Email",body:"info@partyhubballoons.com"},{title:"Location",body:"Yiwu, Zhejiang, China"},{title:"Response preparation",body:"Include reference images, expected quantity, destination, artwork, and packaging requirements for a more precise discussion."}]},
  privacy:{eyebrow:"Privacy",title:"How enquiry information is used.",description:"Information submitted through this website is used to review and respond to product and sourcing enquiries.",sections:[{title:"Information collected",body:"We may collect your name, company, email, phone number, country, product interest, quantity, and message."},{title:"Purpose",body:"Information is used to respond to enquiries, prepare quotations, and coordinate requested business discussions."},{title:"Contact",body:"Questions about submitted information can be sent to info@partyhubballoons.com."}]}
};
