import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BadgeCheck, Factory, Palette, Sparkles } from "lucide-react";
import { company } from "@/content/company";
import { faq } from "@/content/faq";
import { products } from "@/content/products";

export function HomePage({locale}:{locale:string}){return <main>
  <section className="hero dark"><div className="aurora"/><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow"><Sparkles size={14}/>Crafted for standout celebrations</span><h1>Premium Balloons, Made for <em>Remarkable Celebrations.</em></h1><p>Distinctive foil balloons, scalable production, and flexible OEM/ODM support for global party brands, distributors, and event programs.</p><div className="hero-actions"><Link className="button" href={`/${locale}/products`}>Explore Products <ArrowRight size={17}/></Link><Link className="button ghost" href={`/${locale}/contact`}>Request a Quote</Link></div></div><div className="hero-visual"><div className="halo"/><Image src="/media/products/agate-star-foil-balloon.png" alt="Colorful agate star foil balloons" width={900} height={680} priority/></div></div></section>
  <section className="metrics dark"><div className="container metrics-grid">{company.metrics.map(m=><div key={m.label}><strong>{m.value}</strong><span>{m.label}</span></div>)}</div></section>
  <section className="section light"><div className="container"><div className="section-heading"><div><span className="eyebrow">Curated collection</span><h2>Balloon designs with retail impact.</h2></div><Link className="text-link" href={`/${locale}/products`}>View all products <ArrowRight size={16}/></Link></div><div className="product-grid">{products.map(p=><Link data-testid="product-card" className="product-card" href={`/${locale}/products/${p.slug}`} key={p.slug}><div className="product-image"><Image src={p.image} alt={p.name} fill sizes="(max-width:760px) 90vw,31vw"/></div><span>{p.category}</span><h3>{p.name}</h3><p>{p.description}</p><b>Discover product <ArrowRight size={15}/></b></Link>)}</div></div></section>
  <section className="section gradient"><div className="container split"><div className="factory"><Image src="/media/factory/printing-equipment.png" alt="Balloon printing equipment" width={820} height={620}/></div><div><span className="eyebrow"><Factory size={15}/>Built to scale</span><h2>From creative brief to production floor.</h2><p>Printing, metallizing, film blowing, punching, and bag-making capacity support repeatable balloon programs and custom collections.</p><ul>{company.equipment.map(x=><li key={x}><BadgeCheck size={18}/>{x}</li>)}</ul><Link className="button dark-button" href={`/${locale}/manufacturing`}>Explore manufacturing</Link></div></div></section>
  <section className="section dark"><div className="container"><span className="eyebrow">OEM / ODM workflow</span><h2>A clear route from idea to shipment.</h2><div className="process-grid">{[["01","Brief"],["02","Sample"],["03","Production"],["04","Inspection"]].map(([n,t])=><article key={n}><span>{n}</span><h3>{t}</h3><p>Confirm requirements and keep each stage clear, practical, and reviewable.</p></article>)}</div></div></section>
  <section className="section light"><div className="container custom"><div><span className="eyebrow"><Palette size={15}/>Custom collections</span><h2>Your idea. Our production canvas.</h2><p>Build coordinated balloon ranges with custom artwork, color themes, language variants, pack formats, and retail-ready assortments.</p><Link className="button" href={`/${locale}/custom-solutions`}>Start a custom project</Link></div><div className="chips">{["Printed artwork","Color matching","Shape development","Language variants","Retail packs","Assorted sets"].map(x=><span key={x}>{x}</span>)}</div></div></section>
  <section className="section faq"><div className="container"><div className="section-heading"><div><span className="eyebrow">Buyer essentials</span><h2>Practical answers before you enquire.</h2></div></div><div className="faq-grid">{faq.slice(0,4).map(x=><article key={x.question}><h3>{x.question}</h3><p>{x.answer}</p></article>)}</div></div></section>
  <section className="quote dark"><div className="container"><span className="eyebrow">Bring your next collection to life</span><h2>Ready to create something worth celebrating?</h2><p>Tell us what you need, where it will be sold, and the quantity you are planning.</p><Link className="button" href={`/${locale}/contact`}>Request a Quote <ArrowRight size={17}/></Link></div></section>
</main>}
